#!/usr/bin/env bash
# Builds the Pokemon Emerald Android APK from the pokeemerald-multiplatform fork.
#
# This is the native SDL2 port -- the decompiled game code is compiled directly
# for Android. No emulator is bundled and no commercial ROM is used or produced.
#
# Requires: JAVA_HOME, ANDROID_HOME (with NDK + cmake installed, see REQUIRED_*
# below), and an arm-none-eabi binutils on PATH for the game's data/song
# assembly, which is still assembled as ARM and linked into libmain.so.
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/gradenGnostic/pokeemerald-multiplatform.git}"
REPO_REF="${REPO_REF:-master}"
WORK_DIR="${WORK_DIR:-$PWD/.pokeemerald-multiplatform}"

REQUIRED_NDK="26.3.11579264"
REQUIRED_CMAKE="3.22.1"

log() { printf '\n==> %s\n' "$*"; }

: "${ANDROID_HOME:?ANDROID_HOME must point at an Android SDK}"
command -v arm-none-eabi-as >/dev/null || {
    echo "arm-none-eabi-as not found; install binutils-arm-none-eabi" >&2
    exit 1
}

if [ ! -d "$WORK_DIR/.git" ]; then
    log "Cloning $REPO_URL @ $REPO_REF"
    git clone --branch "$REPO_REF" "$REPO_URL" "$WORK_DIR"
fi
cd "$WORK_DIR"

log "Fetching the SDL2 submodule"
git submodule update --init --recursive android/SDL2

# The fork ships a lifecycle patch that strips SDL's Android activity-mutex
# locking out of SDL_CreateRenderer and Android_CreateWindow. It is generated
# with zero context lines, so plain `git apply` -- which is what the fork's
# README tells you to run -- always rejects it. --unidiff-zero is required.
# Applying it twice would also fail, hence the reverse check.
log "Applying the SDL2 Android lifecycle patch"
if git -C android/SDL2 apply -R --check ../patches/sdl2-android-lifecycle.patch 2>/dev/null; then
    echo "already applied, skipping"
else
    git -C android/SDL2 apply --unidiff-zero ../patches/sdl2-android-lifecycle.patch
fi

# The CMake build shells out to tools/preproc/preproc for every .c and .s file.
log "Building the decomp's host tools"
make -j"$(nproc)" tools

# global.h pulls in constants/maps.h, which includes map_groups.h -- a header
# generated by tools/mapjson, not checked in. The Android CMake build never
# runs any of the decomp's generation rules, so without this every translation
# unit fails at the preprocessing step with "'map_groups.h' file not found".
# `generated` covers the whole AUTO_GEN_TARGETS set (map_groups.h, layouts.h,
# map_event_ids.h, the region map and heal location headers, ...).
log "Generating the decomp's generated headers and sources"
make -j"$(nproc)" generated

# INCBIN_*() in the C sources and .incbin in the assembly reference binary
# assets (.4bpp, .gbapal, .lz, .bin, cries...) that gbagfx and friends generate
# from the checked-in PNGs and WAVs. This fork predates pokeemerald's
# build/assets layout -- its preproc has no -g flag -- so the assets have to
# land in the source tree, beside their sources, and the Android CMake build
# generates none of them.
#
# We ask make for exactly the referenced files rather than running `make modern`
# to build the whole ROM, because the ROM build is broken in this fork:
# src/platform/bios.c is SDL port code and does not compile for the GBA target.
log "Generating binary assets referenced by INCBIN"
# Scanning for INCBIN_*(...) is not enough: a single INCBIN_U32() takes several
# comma-separated paths spanning many lines, so a line-oriented match catches
# only the first of each. Match any quoted asset-directory path instead, which
# is independent of the macro syntax. Paths that are already checked-in sources
# (.png, .pal, .aif) are simply no-ops for make; non-asset extensions are
# dropped because some have no make rule at all.
TARGETS="$WORK_DIR/.asset-targets"
grep -rhoE '"(graphics|data|sound)/[^"]*\.[a-z0-9.]+"' src include data sound \
    | tr -d '"' | sort -u > "$TARGETS"
grep -rhoE '\.incbin[[:space:]]+"[^"]+"' data sound \
    | sed -E 's/.*"([^"]+)"/\1/' >> "$TARGETS"
grep -vE '\.(h|c|inc|json|txt|mk|s)$' "$TARGETS" | sort -u -o "$TARGETS"
echo "$(wc -l < "$TARGETS") asset targets"
xargs -a "$TARGETS" make -j"$(nproc)" >/dev/null

# Fail here, with the list, rather than several minutes into the ninja build.
missing=$(while read -r asset; do
    [ -f "$asset" ] || echo "$asset"
done < "$TARGETS")
if [ -n "$missing" ]; then
    echo "ERROR: assets still missing after generation:" >&2
    echo "$missing" | head -20 >&2
    exit 1
fi

# Two more sets of generated sources that `make generated` does not cover,
# because upstream they are prerequisites of the ROM's maps.o / song objects
# rather than members of AUTO_GEN_TARGETS. Both must exist BEFORE Gradle runs,
# since the CMake file globs them at configure time.
#
# Without these the whole game compiles and only the final link fails, with
# undefined gMapGroups (per-map .inc) and undefined se_*/mus_* (song .s).
log "Generating map .inc files"
MAP_INCS="$WORK_DIR/.map-incs"
for dir in data/maps/*/; do
    [ -f "$dir/map.json" ] || continue
    printf '%sheader.inc\n%sevents.inc\n%sconnections.inc\n' "$dir" "$dir" "$dir"
done > "$MAP_INCS"
printf 'data/maps/headers.inc\ndata/maps/groups.inc\ndata/maps/connections.inc\n' >> "$MAP_INCS"
printf 'data/maps/events.inc\ndata/layouts/layouts.inc\ndata/layouts/layouts_table.inc\n' >> "$MAP_INCS"
echo "$(wc -l < "$MAP_INCS") map includes"
xargs -a "$MAP_INCS" make -j"$(nproc)" >/dev/null

# The songs ship as .mid only; mid2agb produces the .s that defines se_* / mus_*.
log "Generating song assembly from MIDI"
ls sound/songs/midi/*.mid | sed 's/\.mid$/.s/' > "$WORK_DIR/.song-asm"
echo "$(wc -l < "$WORK_DIR/.song-asm") songs"
xargs -a "$WORK_DIR/.song-asm" make -j"$(nproc)" >/dev/null

log "Assembling the APK"
BUILD_LOG="${BUILD_LOG:-$WORK_DIR/android-build.log}"
if ! ./android/SDL2/android-project/gradlew -p android :app:assembleDebug \
        2>&1 | tee "$BUILD_LOG"; then
    # The ninja build emits ~1000 lines of progress; surface just the
    # diagnostics so a CI failure is readable without downloading the log.
    log "BUILD FAILED -- compiler diagnostics:"
    grep -E '(fatal )?error:|^\s*FAILED:' "$BUILD_LOG" | sort -u | head -50
    exit 1
fi

APK="android/app/build/outputs/apk/debug/app-debug.apk"
log "Done: $WORK_DIR/$APK"
ls -la "$APK"
